### PR TITLE
Support for XXXHDPI ActionBar icons

### PR DESCRIPTION
**Pull request by johan12345**

### CODE REVIEW

**Comment by bryant1410** [comment]
According to [this](https://developer.android.com/guide/practices/screens_support.html#xxxhdpi-note) xxxhdpi assets are only needed for launcher icons, which are already provided by this tool.

**Comment by johan12345** [comment]
But according to this, the Nexus 6 uses xxxhdpi resources (if available),
not only for the launcher icon.
http://android-developers.blogspot.de/2014/10/getting-your-apps-ready-for-nexus-6-and.html?m=1

**Comment by bryant1410** [comment]
Aw, android documentation must be outdated

**Comment by johan12345** [comment]
Yeah. Especially the design guidelines don't match the new ones at
google.com/design.

**Comment by johan12345** [comment]
This is not needed anymore because #46 has been merged

**Pull request closed without merging**
