### PR TITLE
Adds a service worker using Workbox

### PR DESCRIPTION
**Pull request by jeffposnick**
Hey @romannurik!

If you're cool with it, this PR will add a service worker that precaches all of the critical static content, and then sets up some runtime caching for the third-party Google Fonts and Analytics requests.

You can test it out at https://jeffposnick.github.io/AndroidAssetStudio/

(It doesn't add a web app manifest or handle Add to Homescreen prompts, but that could be done in a follow-up if you're open to it.)

CC: @paulkinlan

### CODE REVIEW

**Comment by romannurik** [comment]
Hey Jeffy thanks for doing this!

My only concern was in @PaulKinlan's [CL on another app of mine](https://github.com/romannurik/SlidesCodeHighlighter/pull/14#issuecomment-401841651), it seemed to break browsersync reload. Would this PR have the same issue?

**Comment by jeffposnick** [comment]
I just pushed out another commit that does two things:

- Uses separate ports for `dev` and `prod`, creating two origins. That means the service worker/cache from one environment won't effect the service worker/cache from the other.

- Put in a dummy, no-op `sw.js` that's used in the `dev` environment, so even though it will be registered, it won't intercept network traffic. That should make browsersync happy.

browsersync won't work as expected in the `prod` environment with the real service worker, because the service worker will intercept requests and used cached responses, but that will match the real-world behavior.

**Comment by romannurik** [comment]
This is perfect thanks Jeffy!

**Comment by romannurik** [comment]
I'll see about doing another release soon that'll include this.

**Comment by jeffposnick** [comment]
Sweet! Thanks for building awesome web apps.

**Pull request merged**
